In [2]:
import numpy as np


def init_w(shape, value=0):
    return np.full(shape, value)

In [3]:
ones = init_w((3, 4), 1)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
angle=np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [6]:
np.random.random((3,3))

array([[0.96433528, 0.36200428, 0.92290366],
       [0.04949743, 0.8767595 , 0.14871116],
       [0.30576438, 0.27300376, 0.56618752]])

In [7]:
np.random.randint(0,11,(5,5))

array([[ 9,  1,  3,  3,  9],
       [ 4,  4,  1,  4,  6],
       [ 0,  1,  7,  5,  4],
       [10,  8,  3,  9,  9],
       [ 5,  8,  5,  3,  6]], dtype=int32)

In [11]:
a=['tspeeh','hassan','mahmoud']
np.random.choice(a,15)

array(['tspeeh', 'tspeeh', 'mahmoud', 'tspeeh', 'hassan', 'mahmoud',
       'mahmoud', 'tspeeh', 'mahmoud', 'tspeeh', 'tspeeh', 'tspeeh',
       'tspeeh', 'tspeeh', 'hassan'], dtype='<U7')

In [18]:
mat=np.ones((3,3))
print(mat)
print("="*20)
mat2=np.zeros((3,3))
print(mat2)
np.savez('myfile.npz', cat=mat, dog=mat2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
====================
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [21]:
with np.load('myfile.npz') as data:
    mat=data['cat']
    mat2=data['dog']
    print(mat)
    print("="*20)
    print(mat2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
====================
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [4]:
import numpy as np
m1=np.array([[1, 2, 3], [4, 5, 6]])
m2=np.array([[9, 8, 7], [6, 5, 4]])
new_m1=np.vstack((m1,m2))
new_m1

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [6]:
vec=np.array([1, 2, 3, 4, 5])
vec2=np.array([6, 7, 8, 9, 10])
vec==vec2

array([False, False, False, False, False])

In [7]:
v=np.array([1,2,23,4,5])
np.all(v>1)

np.False_

In [9]:
v=np.array([1,2,23,4,5])
np.any(v>1)

np.True_

In [13]:
v1=np.array([1,2,3,4,5,6,7])
v2=np.array([85,2,6,38,7,4,5])
np.isclose(v1,v2, atol=1)

array([False,  True, False, False, False, False, False])

In [15]:
v1=np.array([1,2,3,4,5,6,7])
v2=np.array([85,2,6,38,7,4,5])
np.isclose(v1,v2, atol=100)

array([ True,  True,  True,  True,  True,  True,  True])

In [16]:
v1=np.array([1,2,3,4,5,6,7])
v2=np.array([85,2,6,38,7,4,5])
np.allclose(v1,v2, atol=100)

True

In [21]:
v=np.array([5,2,3,6,1,4,5])
c=v>=4
v[c]=-1
print(v)

[-1  2  3 -1  1 -1 -1]

In [22]:
v=np.array([5,2,3,6,1,4,5])
c=4
summation=v+c
print(summation)

[ 9  6  7 10  5  8  9]

In [23]:
import pandas as pd

In [26]:
s=pd.Series([1,2,3,4], index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [33]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
df

   id  sal  dep
0   1  444  abc
1   2  555  def
2   3  666  ghi
3   4  444  xyz

In [34]:
display(df)

   id  sal  dep
0   1  444  abc
1   2  555  def
2   3  666  ghi
3   4  444  xyz

In [38]:
cols=['cols1','cols2','col3']
df.columns=cols
df.columns

Index(['cols1', 'cols2', 'col3'], dtype='str')

In [39]:
df['cols1'].dtypes

dtype('int64')

In [45]:
df['cols1']=df['cols1'].astype("category")
df.dtypes

cols1    category
cols2       int64
col3          str
dtype: object

In [46]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)

In [50]:
df.head(-3)

   id  sal  dep
0   1  444  abc

In [52]:
df.tail(1)

   id  sal  dep
3   4  444  xyz

In [54]:
df.describe()

             id         sal
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [55]:
df.columns

Index(['id', 'sal', 'dep'], dtype='str')

In [57]:
x=df.id.idxmax()
x

3

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64
 1   sal     4 non-null      int64
 2   dep     4 non-null      str
dtypes: int64(2), str(1)
memory usage: 240.0 bytes

In [61]:
df['sal' ].value_counts()

sal
444    2
555    1
666    1
Name: count, dtype: int64

In [64]:
x=df.values
type(x)

numpy.ndarray

In [70]:
sort_df=df.sort_values(by='cols1', ascending=false)
sort_df

NameError: name 'false' is not defined

In [72]:
df['sal'].apply(lambda x : x*2)

0     888
1    1110
2    1332
3     888
Name: sal, dtype: int64

In [73]:
df.sal.iloc[2]

np.int64(666)

In [76]:
x=df.iloc[:,0:2]
x

   id  sal
0   1  444
1   2  555
2   3  666
3   4  444

In [77]:
x=df.iloc[:,-1]
x

0    abc
1    def
2    ghi
3    xyz
Name: dep, dtype: str

In [78]:
df.drop(['sal'],axis=1)

   id  dep
0   1  abc
1   2  def
2   3  ghi
3   4  xyz