In [7]:
import pandas as pd
pd.read_csv('data.csv',sep=',')

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [8]:
pd.read_csv('data.csv',sep='#')

    Duration,Pulse,Maxpulse,Calories
0                   60,110,130,409.1
1                   60,117,145,479.0
2                   60,103,135,340.0
3                   45,109,175,282.4
4                   45,117,148,406.0
..                               ...
164                 60,105,140,290.8
165                 60,110,145,300.0
166                 60,115,145,310.2
167                 75,120,150,320.4
168                 75,125,150,330.4

[169 rows x 1 columns]

In [10]:
pd.read_csv('data.csv',na_values='60')

     Duration  Pulse  Maxpulse  Calories
0         NaN    110       130     409.1
1         NaN    117       145     479.0
2         NaN    103       135     340.0
3        45.0    109       175     282.4
4        45.0    117       148     406.0
..        ...    ...       ...       ...
164       NaN    105       140     290.8
165       NaN    110       145     300.0
166       NaN    115       145     310.2
167      75.0    120       150     320.4
168      75.0    125       150     330.4

[169 rows x 4 columns]

In [11]:
pd.read_csv('data.csv',index_col=['Pulse'])

       Duration  Maxpulse  Calories
Pulse
110          60       130     409.1
117          60       145     479.0
103          60       135     340.0
109          45       175     282.4
117          45       148     406.0
...         ...       ...       ...
105          60       140     290.8
110          60       145     300.0
115          60       145     310.2
120          75       150     320.4
125          75       150     330.4

[169 rows x 3 columns]

In [16]:
pd.read_csv('data.csv',header=None)

            0      1         2         3
0    Duration  Pulse  Maxpulse  Calories
1          60    110       130     409.1
2          60    117       145     479.0
3          60    103       135     340.0
4          45    109       175     282.4
..        ...    ...       ...       ...
165        60    105       140     290.8
166        60    110       145     300.0
167        60    115       145     310.2
168        75    120       150     320.4
169        75    125       150     330.4

[170 rows x 4 columns]

In [17]:
pd.read_csv('data.csv',nrows=3)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0

In [18]:
pd.read_csv('data.csv',skiprows=3)

     60  103  135  340.0
0    45  109  175  282.4
1    45  117  148  406.0
2    60  102  127  300.0
3    60  110  136  374.0
4    45  104  134  253.3
..   ..  ...  ...    ...
161  60  105  140  290.8
162  60  110  145  300.0
163  60  115  145  310.2
164  75  120  150  320.4
165  75  125  150  330.4

[166 rows x 4 columns]

In [19]:
df=pd.read_csv('data.csv',sep=',')
df.set_index('Duration')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [20]:
df .info()

<class 'pandas.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [21]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [26]:
df[['Duration', 'Pulse']].head()
df.loc[[2,3]]

   Duration  Pulse  Maxpulse  Calories
2        60    103       135     340.0
3        45    109       175     282.4

In [27]:
df.loc[[2,3],['Duration', 'Pulse'] ]

   Duration  Pulse
2        60    103
3        45    109

In [28]:
df.iloc[1]

Duration     60.0
Pulse       117.0
Maxpulse    145.0
Calories    479.0
Name: 1, dtype: float64

In [32]:
df.iloc[:1,:5]

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1

In [33]:
df['new']=df['remo']*df['salary']
df.head()

KeyError: 'remo'

In [34]:
df.drop([1],axis=0)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[168 rows x 4 columns]

In [35]:
df['Duration'].unique()

array([ 60,  45,  30,  80,  20, 210, 160, 180, 150, 300,  90, 120, 270,
        15,  25,  75])

In [36]:
df['Duration'].nunique()

16

In [37]:
df['Duration'].value_counts()

Duration
60     79
45     35
30     16
20      9
90      8
150     4
180     3
120     3
210     2
160     2
15      2
75      2
80      1
300     1
270     1
25      1
Name: count, dtype: int64

In [38]:
df['Duration'].value_counts().sort_values()

Duration
80      1
300     1
270     1
25      1
210     2
160     2
15      2
75      2
120     3
180     3
150     4
90      8
20      9
30     16
45     35
60     79
Name: count, dtype: int64

In [42]:
pd.crosstab(df["Pulse"],df["Calories"], normalize="index")

Calories,50.3,50.5,77.7,86.2,92.7,100.7,105.3,110.4,124.0,124.2,...,853.0,873.4,953.2,1000.1,1034.4,1115.0,1376.0,1500.2,1729.0,1860.4
Pulse,,,,,,,,,,,,,,,,,,,,,
80,0.0,0.5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
83,1.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
85,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
90,0.0,0.0,0.000000,0.090909,0.000000,0.000000,0.090909,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
92,0.0,0.0,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
93,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
95,0.0,0.0,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
97,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.166667,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
100,0.0,0.0,0.000000,0.000000,0.000000,0.052632,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.052632,0.000000,0.000000,0.000000,0.000000,0.052632,0.0
101,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
102,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
103,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
104,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
105,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
106,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
107,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
108,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.142857,0.142857,0.000000,0.0
109,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.111111,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
110,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.142857,0.000000,0.000000,0.000000,0.000000,0.0
111,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
112,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
113,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
114,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
115,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
116,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
117,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
118,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
119,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
120,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
121,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
122,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
123,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
124,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
125,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
129,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
130,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
136,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
137,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0
141,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
149,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
150,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
151,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
152,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
153,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
159,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [43]:
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df[df['Pulse']>110]

     Duration  Pulse  Maxpulse  Calories
1          60    117       145     479.0
4          45    117       148     406.0
22         60    130       101     300.0
35         60    114       140     415.0
43         60    111       138     400.0
44         60    111       131     397.0
47         45    111       136     300.0
49         60    111       139     397.6
51         80    123       146     643.1
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
63         45    118       141     341.0
74         45    114       146     304.0
80         30    159       182     319.2
81         45    149       169     344.0
85         30    151       170     300.0
88         45    129       103     242.0
94         20    150       171     127.4
95         20    151       168     229.4
97         25    152       168     244.2
109       210    137       184    1860.4
112        15    124       139     124.2
116        60    116       141     443.0
120        30    112       137     193.9
122        60    119       169     336.7
124        60    111       151     368.5
129        60    114       151     384.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
143        45    122       149     335.4
144        60    136       170     470.2
147        60    112       146     361.9
153        30    150       167     275.8
155        60    111       151     368.5
158        60    114       150     382.8
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [49]:
df.isna().sum().sort_values().head(7)

Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

In [51]:
df=df.dropna()

In [52]:
df.dropna(subset=['Calories'], axis=0)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[164 rows x 4 columns]

In [54]:
df.reset_index(drop=True, inplace=True)

In [55]:
df.fillna(value='555')

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
159        60    105       140     290.8
160        60    110       145     300.0
161        60    115       145     310.2
162        75    120       150     320.4
163        75    125       150     330.4

[164 rows x 4 columns]

In [56]:
df[df['Calories']==555]

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

In [58]:
df.shape

(164, 4)

In [59]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
159    False
160    False
161    False
162    False
163    False
Length: 164, dtype: bool

In [60]:
df.drop_duplicates()

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
159        60    105       140     290.8
160        60    110       145     300.0
161        60    115       145     310.2
162        75    120       150     320.4
163        75    125       150     330.4

[157 rows x 4 columns]

In [61]:
def times2(x):
    return x*2

In [63]:
df['Duration'].apply(times2).head()

0    120
1    120
2    120
3     90
4     90
Name: Duration, dtype: int64

In [64]:
df.shape

(164, 4)

In [66]:
com=df.groupby('Duration')
com.head()

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
18         45     97       125     243.0
20         45    100       119     282.0
49         80    123       146     643.1
52         30    136       175     238.0
56         20    153       172     226.4
58        210    108       160    1376.0
59        160    110       137    1034.4
60        160    109       135     853.0
62         20    110       130     131.4
63        180     90       130     800.4
64        150    105       135     873.4
65        150    107       130     816.0
66         20    106       136     110.4
67        300    108       143    1500.2
68        150     97       129    1115.0
70         90    100       127     700.0
71        150     97       127     953.2
73         90     98       125     563.2
76        120    100       130     500.4
77        270    100       131    1729.0
78         30    159       182     319.2
80         30    103       139     151.1
81        120    100       130     500.0
83         30    151       170     300.0
85        120    100       157    1000.1
87         20     83       107      50.3
88        180    101       127     600.1
90         15     80       100      50.5
91         20    150       171     127.4
94         25    152       168     244.2
96         90     93       124     604.1
98         90     90       110     500.0
99         90     90       100     500.0
103       180     90       120     800.3
106       210    137       184    1860.4
109        15    124       139     124.2
162        75    120       150     320.4
163        75    125       150     330.4

In [67]:
com=df.groupby('Duration')['Duration'].mean()
com.head()

Duration
15    15.0
20    20.0
25    25.0
30    30.0
45    45.0
Name: Duration, dtype: float64